#!/bin/sh

script_dir=$(dirname "$0")

echo "Setting up requirements for dscripts"

if ! py -3 -c "exit()" &>/dev/null; then
    echo "ERROR: No Python3 installation found!"
    exit 1
fi

echo "Installing pip dependencies"
pip install -r $script_dir/requirements.txt

echo "Success!"